### ISSUE TITLE
vim-kaoriyaの配布するVim8、pythonのバージョンを3.6以上にしてほしい。

### ISSUE THREAD

**Issue by takkii** [koron/vim-kaoriya#23]
Python3.6 or Python3.7に対応してほしい。

それにより、deoplete、denite、defxなどのPython3.6以上を使うプラグインを試せるので、

できれば対応して欲しい。

**Comment by koron** [comment]
コンパイラの変更が必要になり、時間を食うので腰が重い状態。

**Comment by takkii** [comment]
気長に待ちます。Python3.6に変わったときに、issuesを閉じてください。

**Comment by kyouryuukunn** [comment]
"set pythonthreedll"すればそれでよいのでは？
winで軽く試した感じ、python3.7は互換性の関係かdeprecationwarning出るけど3.6はいけそう

**Comment by takkii** [comment]
わかりました。issuesは閉じます。そもそもWSLが使えるので、Windowsでkaoriya-vimが欲をいえばPython3.6以降に対応したらいいなぁと要望だっただけなので。それはしないけど。
