### ISSUE TITLE
luaでvim.list, vim.dictが動作しない

### ISSUE THREAD

**Issue by kyouryuukunn** [koron/vim-kaoriya#24]
vim.list, vim.dictが引数にかかわらず、空のリスト、辞書を返す。

再現手順
vim --noplugin
ヘルプに従い、以下のコマンドを実行する
:lua t = {math.pi, false, say = 'hi'}
:echo luaeval('vim.list(t)')

vim.dictに関しても同じ状況です。

:echo has('lua')
では1を返し、
:echo luaeval('1+1')
など、他のlua関係は動作しているようです。
他にluaが有効なvimがないため、vim自体の問題かは分かりませんでした。

windows 10 x64
vim81-kaoriya-win64-8.1.0005-20180520

**Comment by k-takata** [comment]
正確なバージョンは分かりませんが、Vim 8.1.0134 ~ 0183 のどこかで直ったものと思われます。

> 他にluaが有効なvimがないため、vim自体の問題かは分かりませんでした。

https://github.com/vim/vim-win32-installer/releases で公開されているナイトリービルドも試してみてください。

**Comment by kyouryuukunn** [comment]
ありがとうございます。
ナイトリービルド版で正常動作を確認できました。
