### ISSUE TITLE
GUIオプションが使用できない

### ISSUE THREAD

**Issue by beckorz** [koron/vim-kaoriya#27]
いつも利用させていただきありがとうございます。
早速、最新の 8.2.0029 のGVimにてGUIオプションを使用したところ、

```
E25: GUIは使用不可能です: コンパイル時に無効にされています
```

のエラーが出てGUIオプションを使用できませんでした。
transparency等のGUI系のオプション等が使用できない状態になります。なお、以前までのバージョンでは使用可能でした。

バージョン詳細は以下です。
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 22 2019 20:42:15)
MS-Windows 64 ビット GUI/コンソール 版
適用済パッチ: 1-29
```

**Comment by koron** [comment]
https://github.com/vim-jp/issues/issues/1323 で対応を開始。
一部 +kaoriya 固有の症状ですが、
そうでなさそうな部分もあるのでしばらくは向こうでやりましょう。

**Comment by koron** [comment]
問題整理。以下の問題は +kaoriya版固有のものでありこちらで対応します。

* .vimrc で設定した `transparency` が機能しない
* .vimrc で設定した `guifont` が $VIM/gvimrc で上書きされ無効になる

E25 については引き続き https://github.com/vim-jp/issues/issues/1323 でやります。

@beckorz 

`transparency` についてはソースコードの修正が必要なので後日ちゃんと見ます。

`guifont` についてはとりあえず .gvimrc で設定するように変更してください。
$VIM/gvimrc については、こちらも後日修正します。

**Comment by koron** [comment]
> $VIM/gvimrc については、こちらも後日修正します。

```vim
  " Windows用フォント
  if &guifont == ''
    set guifont=MS_Gothic:h12:cSHIFTJIS
  endif
```

こんなふうに修正予定

**Comment by koron** [comment]
@beckorz 

develop 版で修正してみましたので、お時間のある時に以下の配布ファイルを試してみてください。

https://files.kaoriya.net/vim/vim82-kaoriya-win64-8.2.0046-20191227.zip
https://files.kaoriya.net/vim/vim82-kaoriya-win32-8.2.0046-20191227.zip

[netupvim](https://github.com/koron/netupvim) を使ってる場合は開発版もしくは人柱版でも入手できます。
参考: [開発版の利用](https://github.com/koron/netupvim#%E9%96%8B%E7%99%BA%E7%89%88%E3%81%AE%E5%88%A9%E7%94%A8)

**Comment by beckorz** [comment]
@koron 

早々の対応ありがとうございます。確認してみました。
今現在自分で設定している gvimrc で設定している項目だと以下の結果です。

- [x] :gui無しでもエラーメッセージ無しで動作
- [x] set transparency
- [x] set guifont
- [x] set guifontwide
- [x] set renderoptions=type:directx
- [x] winpos
- [ ] set columns
- [ ] set lines

set columns, set lines が上書きされているようで、起動後 set columns, set lines で有効になりますが、それ以外は想定通りの動きです。

**Comment by beckorz** [comment]
すみません。追記です。

- [ ] colorscheme
- [ ] hi ～ の色設定

の色設定も駄目でした。

**Comment by koron** [comment]
@beckorz

`coloumns` や `lines` は .vimrc で設定してたら反映されないってことですよね。
それらは本来 .gvimrc で設定してほしいのですよね。

あと `:gui` コマンドは以下のPRで復活するんで…
https://github.com/vim/vim/pull/5408 

対応が難しい。

**Comment by beckorz** [comment]
@koron 

恥ずかしながら、当方のvimrc, gvimrcの違いをそもそもきちんと理解していなかった事に起因する事項との事で理解しました。
今まではきちんとgvimrcでの設定を分けておらず、vimrcのみで`has('gui_running')`でGUI判断して行っておりました。指摘の通りvimrc、gvimrcに設定分離して想定通りの動きにできました。(colorschemeは、vimrcとgvimrc毎に設定するのは盲点でした)

`:gui`に関しては、今後復活するとの事で、最悪vimのバージョンを判定してやろうかそれは当方で検討いたします。
