### ISSUE TITLE
日本語のヘルプが開かない

### ISSUE THREAD

**Issue by azarashichop** [koron/vim-kaoriya#28]
`set helplang=jp`となっているんですが、ヘルプを開くと英語のヘルプが表示されます。
plugins\vimdoc-jaディレクトリがあることも確認済です。

![image](https://user-images.githubusercontent.com/8552118/94551603-913a5f00-0290-11eb-9a18-36abbb1eba93.png)

**Comment by koron** [comment]
1. `$VIM\switches\enabled\disable-vimdoc-ja.vim` がないことを確認してください

   このファイルがあると強制で日本語マニュアルが無効化されます。

2. `:verbose set rtp` の結果を貼ってください

    rtp に $VIM\pluginsk\vimdoc-ja が含まれている必要があります。

3. `:scriptnames` で $VIM\vimrc を読み込んでいるか確認してください

   上記のパスをrtpに含める設定が $VIM\vimrc に含まれています。

**Comment by azarashichop** [comment]
コメントありがとうございます。
2.と3.を確認して、原因特定及び解消しました。

vimrcがvimrcaにリネームされてしまっていたことが原因でした。ありがとうございました！
