### ISSUE TITLE
READMEの記述内容が一部古い

### ISSUE THREAD

**Issue by azarashichop** [koron/vim-kaoriya#29]
Pull Requestの方が良いのかもしれませんが・・・

1. Pythonとの連携セクションに、Python2.7の記述が残っている（2系はサポートドロップした認識です）。
1. Rubyとの連携セクションに記述のある、Ruby2.6.1がサイトから入手できない。

ご確認いただければ幸いです。

**Comment by koron** [comment]
ありがとうございます。

もうしわけないですが +if_python はドロップ予定です。ドキュメントからも削除予定となります。

それが必要な場合はコチラをご利用ください。
https://github.com/vim/vim-win32-installer/
