### ISSUE TITLE
リリースファイル名にVimのバージョンを入れてほしい

### ISSUE THREAD

**Issue by k-takata** [koron/vim-kaoriya#3]
現在のリリースファイル名は、`vim74-kaoriya-winXX-YYYYMMDD.zip` のようになっています。`vim74-kaoriya-winXX-YYYYMMDD-v7.4.XXX.zip` のようにVimのバージョンが入っていると分かりやすいと思うのですがいかがでしょうか。

以下のようなコマンドでVimのバージョンを環境変数に取り込めます。

```batch
for /f %%i in ('git describe --tags --abbrev^=0') do set VIMVER=%%i
```

`--abbrev^=0` は、タグが打たれたあとにruntimeの更新があった場合に、余分な文字列が後ろにつくのを避けるためです。（`^`はエスケープ）

**Comment by koron** [comment]
いまどう変えるか検討中で、とりあえず4案くらいあります。

* vim74-kaoriya-win32-1459-20160229.zip
* vim74-kaoriya-win32-7.4.1459-20160229.zip
* vim74+kaoriya-win32-1459+20160229.zip
* vim74+kaoriya-win32-7.4.1459+20160229.zip

冗長さを廃して既存のものに近いというところでは以下ですが、

    vim74-kaoriya-win32-1459-20160229.zip

意味合い的に正しくて理解しやすそうなのはこっちかなって考えてます。

    vim74+kaoriya-win32-1459+20160229.zip

余談ですが vim+kaoriya-win32-7.4.1459+20160229.zip にしないのは
展開後のディレクトリにバージョンを示す 74 を含めることで
74 と将来の 75 を混乱なく両方を共存インストールして移行のバッファにすることを意図しています。
…が、これももう要らないかしら?

**Comment by k-takata** [comment]
私としては、`7.4.1459` が一続きになっているほうが分かりやすいと思います。
冗長なのは、まあ許容の範囲内かなと。

**Comment by koron** [comment]
んじゃあ、もう `vim+kaoriya-win32-7.4.1459+20160229.zip` にしちゃおうかしら?
展開後のディレクトリは `vim+kaoriya-win32` で。

**Comment by k-takata** [comment]
> 74 と将来の 75 を混乱なく両方を共存インストールして移行のバッファにすることを意図しています。

7.3から7.4への以降の際には、これを使ってしばらく(NFAが安定するまで)共存させていました。

**Comment by koron** [comment]
アレはリリースエンジニアリングがアレなだけで(震え声

**Comment by k-takata** [comment]
まあ、アレがアレだった点に異存はないので、次のリリースがアレでないことを期待して74を削除するかどうかはおまかせします。
あー、でもディレクトリ名の変更は次のリリースのタイミングの方がいいような気も…。（いつになるのやら）

**Comment by koron** [comment]
例えば、しばらくは2バージョンリリースして、リリースのタイミングで旧名のほうをカットする、とかで良いのかも。

で、新名のほうはgithubのreleaseで、みたいな。

**Comment by koron** [comment]
とりあえずは次のリリースから `vim74-kaoriya-win32-7.4.1459-20160229.zip` の形式で行くことにしました。

リリースに github release と netupvim を使うようになったため、
もろもろ手間が下がって配布ファイル名変更の前提条件を満たしたので。

**Comment by koron** [comment]
次のリリースに伴い、本 issue は閉じます。
