### ISSUE TITLE
:Scratch コマンドの、ファイル名指定 write 時に、scratch解除するハンドラが 動作していない

### ISSUE THREAD

**Issue by KSR-Yasuda** [koron/vim-kaoriya#30]
[`:Scratch`コマンド](https://github.com/koron/vim-kaoriya/blob/d371c3b8bb57ef2ee56570ce5f899d6d11cf69a0/kaoriya/vim/plugins/kaoriya/plugin/cmdex.vim#L84-L96)
で作成した scratchバッファの、
ファイル書込み時の scratch解除のハンドル (`s:CheckScratchWritten()`) が、期待通り 動作していないようです。

`s:CheckScratchWritten()` の期待としては：
scratchバッファを `:write NEW_FILE.txt` として 新しいファイルを作った時に、
scratch解除して、新しい `NEW_FILE.txt` のバッファ としたい；
ということだと思います。

が、どうも、scratchバッファを `:write NEW_FILE.txt` しても、
buffer名 (`%`) が変わらず、scratchの解除条件 に引っ掛からないようです。

以前は 動作していた気がするので、vim本体側の仕様変更 かなにかではないかと。

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 24 2020 11:05:54)
MS-Windows 64 ビット GUI/コンソール 版
適用済パッチ: 1-1287
Modified by koron.kaoriya@gmail.com
Compiled by koron.kaoriya@gmail.com
```

**Comment by KSR-Yasuda** [comment]
`buftype=nofile` の設定を、Vimの挙動によらず `s:CheckScratchWritten()` のスクリプト側でいじるの は良くない気がするので；
`buftype=nofile` を手動解除した上で `write`したケース を考慮したほうが妥当かも。

* `setl buftype=` → `write NEW_FILE.txt`
* `setl buftype=` → `f NEW_FILE.txt` → `write`
    - いずれも、`%` が `NEW_FILE.txt` になっているはず

```diff
 function! s:CheckScratchWritten()
-  if &buftype ==# 'nofile' && expand('%').'x' !=# 'x' && exists('b:cmdex_scratch') && b:cmdex_scratch == 1
-    setlocal buftype= swapfile
+  if exists('b:cmdex_scratch') && b:cmdex_scratch == 1 && expand('%').'x' !=# 'x'
+    set buftype< swapfile<
     unlet b:cmdex_scratch
   endif
 endfunction
```

**Comment by koron** [comment]
9.0.639 で再現を確認しました。

Scratchバッファを `:w foo.txt` した際に
BufWritePost のタイミングでは buftype=nofile ではなくなってるらしい。
(こちらは未確認で推測)

さらに推測だが
以前は Scratch バッファでの  `:w foo.txt` 自体はバッファを作らなかった ≒ バッファ名を変えて保存していたが
現在はバッファはいじらず別名で保存するという処理になっていると考えられる。

どうするかはまだ未定。なにが起こってるのか要検証。

**Comment by koron** [comment]
references:
* https://github.com/vim/vim/issues/5807
* https://github.com/vim/vim/issues/11171

**Comment by koron** [comment]
たぶんコレが原因で挙動が変わったんやなかろか? 
https://github.com/vim/vim/issues/5807

**Comment by koron** [comment]
何が起こったかはおおよそわかった。
どう対処するかは要検討。

**Comment by koron** [comment]
> BufWritePost のタイミングでは buftype=nofile ではなくなってるらしい。

これは間違い。bt=nofileのままだった。

> 現在はバッファはいじらず別名で保存するという処理になっている

これはあってた。よって `expand('%').'x' !=# 'x'` が合致せず。
つまり bt=nofile のとき `:w foo.txt` でバッファに名前が付かなくなってる、と。

**Comment by koron** [comment]
無名バッファについては `:w foo.txt` でバッファに foo.txt という名前が付く。
無名かつbuftype=nofileなバッファについては `:w foo.txt` でもバッファに名前は付かない。

この非直交性はdocumentedかしら? intendedかしら?

**Comment by koron** [comment]
```
 	nofile only:	The buffer name is fixed, it is not handled like a
 			file name.  It is not modified in response to a |:cd|
 			command.
```

**Comment by koron** [comment]
`expand('<afile>')` を見て、空でなければ解除か。

**Comment by koron** [comment]
s:CheckScratchWritten() を次のように変えると、以前の動作に近づきそう。

以下のテストをしてる
* `:w` - バッファ名を省略して書き込みに失敗する
* `:w foo.txt` - foo.txtは存在せず、ファイルの新規作成&書き込み&scratchの解除(名前付け)に成功する
* `:w exist.txt` - exist.txtが存在するので、ファイルの上書きに失敗する
* `:w! exist.txt` - 既存の exist.txt を上書きし、scratchの解除(名前付け)に成功する

```vim
function! s:CheckScratchWritten()
  if &buftype ==# 'nofile' && get(b:, 'cmdex_scratch', 0) == 1 && expand('<afile>') !=# ''
    unlet b:cmdex_scratch
    setlocal buftype= swapfile
    execute "edit!" expand('<afile>')
  endif
endfunction
```

差分

```diff
 function! s:CheckScratchWritten()
-  if &buftype ==# 'nofile' && expand('%').'x' !=# 'x' && exists('b:cmdex_scratch') && b:cmdex_scratch == 1
-    setlocal buftype= swapfile
+  if &buftype ==# 'nofile' && get(b:, 'cmdex_scratch', 0) == 1 && expand('<afile>') !=# ''
     unlet b:cmdex_scratch
+    setlocal buftype= swapfile
+    execute "edit!" expand('<afile>')
   endif
```

**Comment by koron** [comment]
9.0 で修正予定。
8.2系列にはバックポートしないので、上述の差分をユーザーごとに適用してもらう

以上、本件は終了します。
