### ISSUE TITLE
vim-jp/lang-jaを活用する

### ISSUE THREAD

**Issue by k-takata** [koron/vim-kaoriya#4]
日本語言語ファイルは現在 [vim-jp/lang-ja](https://github.com/vim-jp/lang-ja) で管理されており、このリポジトリの contrib ディレクトリの中にも lang-ja が submodule として取り込まれていますが、現在のビルドスクリプトでは lang-ja のファイルはビルドされていません。lang-ja を活用するようにしていただきたいです。

（lang-ja の方で、ビルドスクリプトや更新手順を確立してからということになるかもしれませんが。）

**Comment by koron** [comment]
19e4f43 で lang-ja の各種ファイルを使うようにしてみました。

**Comment by koron** [comment]
lang-ja は make で こっちが nmake だったため、
lang-ja のほうの cp がワイルドカードを含むケースで
INSTALL_DIR をこっちから指定してコピーすることができませんでした。

そのため lang-ja の make test で必要なファイルをビルド後に、
こっちでコピーするというちょっとイケてない感じになってます (´・ω・`)

**Comment by k-takata** [comment]
:+1:
