### ISSUE TITLE
20150926版の同梱しているvimprocでエラー

### ISSUE THREAD

**Issue by beckorz** [koron/vim-kaoriya#5]
いつもvim使わせて貰っています。

vim74-kaoriya-win64-20150926.zip で確認したのですが、同梱しているvimproc_win64.dll を使うとエラーが出るようです。尚 Win7 Enterprise 64bit+Win8 Enterprise 64bitで確認出来ました。尚他の環境ではまだ確認出来ていません。(vimproc_win32.dll や、32bitOSや、Win10等では現在未確認)

```sh
:VimProcBang echo
```

を実行すると、

```sh
vimproc: vp_pipe_open: ['vp_stack_from_buf: no EOV']
vimproc: Error occurred in calling s:vp_pipe_open()
```

とエラー吐きます。尚、一個前(20150728版)に同梱している物は正常に使用出来る事は確認しております。

**Comment by koron** [comment]
https://github.com/Shougo/vimproc.vim/pull/216 これ、ですかね。

**Comment by beckorz** [comment]
レスありがとうございます。

うーん。その内容なのかちょっと分からなくなってきました。
というのも20150728版に含まれていたvimproc(2015-09-25 725de1a)を
自前でmsvcでコンパイルしたdllだと動作が問題無かったので、何か環境依存なのでしょうかね・・・

とりあえず、全然動かないわけじゃないので、次のvimprocが入るvimで確認してみます。

**Comment by beckorz** [comment]
Vim 7.4.1016 (2016/01/01版) をのvimproc_win64.dll を使用したら問題ありませんでした。
クローズします。
