### ISSUE TITLE
20160409版起動時にメッセージがでる。

### ISSUE THREAD

**Issue by robotan** [koron/vim-kaoriya#9]
20160409版64bitをダウンロードして起動したところ、

C:\LocalProgramFiles\vim\vim74\pack\dist\opt\editexisting\plugin\editexist
ing.vim の処理中にエラーが検出されました:
行   66:
E122: 関数 <SNR>15_EditElsewhere は定義済です, 再定義するには ! 
を追加してください

というメッセージが表示されます。(その後の動作的には問題なさそう)
以前は20160228版をつかっていてそのときは特にメッセージは出ませんでした。
どうすればメッセージでなくなるのでしょうか。

**Comment by koron** [comment]
@robotan `packadd editexisting` が .vimrc などに 2回書かれていたりしないでしょうか?

editexisting は2度ロードできない構造になっているようなので、1回だけ `packadd` するようにしてみてください。

**Comment by koron** [comment]
おそらく .vimrc で `packadd editexisting` していると思われますが、
これに `!` を追加して `packadd! editexisting` という風に変更してください。 

参考: [editexisting.vim#L5](https://github.com/vim/vim/blob/a4d13de8363abf4c12fe99a52b4e49e763de92fe/runtime/pack/dist/opt/editexisting/plugin/editexisting.vim#L5)

**Comment by k-takata** [comment]
> おそらく .vimrc で packadd editexisting していると思われますが、

`runtime macros/editexisting.vim` としていたのではないでしょうか。その場合でも、`packadd! editexisting` に変更すればOKです。

7.4.1674, 7.4.1677 で editexisting がパッケージに変更された影響です。

**Comment by koron** [comment]
@k-takata `func!` 使ってくれれば良い気もしますしね…

**Comment by robotan** [comment]
ご指摘の通り、runtime macros/editexisting.vim になっていました。
packadd! editexisting
に変更して、改善しました。ありがとうございました。
